apiVersion: v1
kind: Service
metadata:
  name: docker-java-sample-webapp
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
  selector:
    app: docker-java-sample-webapp